# Experiment BM1

## Building Markov Chain

```{r}
# Clear all
rm(list=ls()); graphics.off()

############## Build
library(markovchain)
library(diagram)
source("MFMC_helper.R")

################################### Start main script ################################### *** Custom logic ***
###### Manual fill 
ITERATIONS_COUNT <- 10^4
basic_states <- list('Su','Sd','Sh', 'Sl')
Su_idx <- 1
Sd_idx <- 2
Sh_idx <- 3
Sl_idx <- 4

D <- 0.85 # probability of fault detection
L <- 0.1 # probability of going to learn state after Sd fail
lambda_d <- 10^-4 
lambda_l <- 1/4
m_u <- 1/4

# |1-λd,     λd*D,  λd*(1-D), 0    |
# |µu*(1-L), 1-µu,  0,        µu*L |
# |0,        λd*D,  (1-D*λd), 0    |
# |0,        0,     0,        1-λl |

transition_matrix_1fragment <-  matrix(c(1-lambda_d,lambda_d,lambda_d,0, 
                                         m_u*(1-L),1-m_u,0,m_u*L, 
                                         0,lambda_d,1,0, 
                                         0,0,0,1-lambda_l),
                                      byrow = TRUE, length(basic_states))
count <- 3
link_data <- list(from = 4, to = 1, value = lambda_l)

transform_D <- linear_transform

# Изменение фрагментов - (функция описания(как объединить параметры и изм. Параметры), параметры, изменяемый параметр, функция измерения параметра)
build_next_fragment <- function(basic_params, D) {
  basic_params[Su_idx, Sd_idx] <- basic_params[Su_idx, Sd_idx] * D
  basic_params[Su_idx, Sh_idx] <- basic_params[Su_idx, Sh_idx] * (1 - D)
  basic_params[Sh_idx, Sd_idx] <- basic_params[Sh_idx, Sd_idx] * D
  basic_params[Sh_idx, Sh_idx] <- 1 - basic_params[Sh_idx, Sd_idx]
  
  return(basic_params)
}

# linking element will be unlinked from the fragment chain + weight will be distributed
transform_last_fragment <- function(fragment, link_data) {
  weight_to_distribute <- fragment[Sd_idx, Sl_idx]
  fragment[Sd_idx, Su_idx] <- fragment[Sd_idx, Su_idx] + weight_to_distribute # add weight to Su
  
  return(fragment)
}

MFMC <- generate_MFMC(transition_matrix_1fragment, basic_states, count, 
                      link_data, transform_last_fragment, build_next_fragment, D, transform_D)

transElms <- MFMC$final_matrix
transElms <- transElms[1:(nrow(transElms) - 2), 1:(ncol(transElms) - 2)] # cut 2 last els, last Sh and Sl must be excluded
all_state_labels <- MFMC$all_state_labels[1:ncol(transElms)] # cut 2 last elemetns
INITIAL_STATE <- c(1, 0, 0, 0, 0, 0, 0 ,0 ,0 ,0) 
print(transElms)

markov <- new('markovchain',
              transitionMatrix = transElms,
              states = all_state_labels,
              name = "BM1")
```

## Visualize MC

```{r}
x_pos <- rep(seq(0.1, 0.9, length = (2 * count)), each = 2) # 2 last elements were deleted
x_pos <- x_pos[1:(length(x_pos)-2)] # 2 last elements were deleted
y_pos <- rep(c(0.7, 0.3, 0.3, 0.7), times = count)
y_pos <- y_pos[1:(length(y_pos)-2)] # 2 last elements were deleted
plotmat(t(transElms),
        relsize = 1,
        pos = cbind(x_pos, y_pos), 
        lwd = 1, # arrow shadow
        box.lwd = 2, shadow.size = 0.003, # shadow
        cex.txt = 0.8, # weight font size
        box.size = 0.03, # state shape size
        box.col = "light blue",
        arr.width = .1, arr.length = .3, arr.pos = 0.4,
        self.cex = .8,
        self.shifty = -.027,
        self.shiftx = -.045,
        main = "Multi Fragment Markov Chain - BM1")
```

## Readiness function calculation

```{r}
calculate_readiness <- function(state_probs_vector) {
  indecies <- seq(1, 12, 4) # every 4 * n + 1 is the Su - up state
  return (sum(state_probs_vector[indecies]))
}

#INITIAL_STATE * markov ^ i = probability vector of being at each state on the "i" step
readiness_over_time <- sapply(0:ITERATIONS_COUNT, function(i)  calculate_readiness(INITIAL_STATE * markov ^ i)) 

# plot
#plot(readiness_over_time, ylab="A(t) - readiness function", xlab="t", type="l", col="red", lwd = 2)
#grid(nx = NULL, ny = NULL,
#     lty = 1,      # Grid line type
#     col = "gray", # Grid line color
#     lwd = 1)      # Grid line width
```

# \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\--

## BM1 without learning (BM1WL)

```{r}
# reuse 1fragment matrix without learnig step + add prob of Sl => Sd to Sd => Su
transElms_without_learning <- transElms[1:3, 1:3] 
transElms_without_learning[2,1] <- transElms[2,1] + transElms[2, 4]

print(transElms_without_learning)

markov_without_learning <- new('markovchain',
              transitionMatrix = transElms_without_learning,
              states = all_state_labels[1:3],
              name = "BM1WL")
```

## Visualize BM1WL

```{r}
plotmat(t(transElms_without_learning),
        relsize = 1,
        pos = NULL, 
        lwd = 1, # arrow shadow
        box.lwd = 2, shadow.size = 0.003, # shadow
        cex.txt = 0.8, # weight font size
        box.size = 0.03, # state shape size
        box.col = "light blue",
        arr.width = .1, arr.length = .3, arr.pos = 0.4,
        self.cex = .8,
        self.shifty = -.027,
        self.shiftx = -.045,
        main = "Markov Chain - BM1 without learning")
```

### Readiness calc for BM1WL

```{r}
INITIAL_STATE_WL <- c(1, 0, 0) # Su
calculate_readiness_wl <- function(state_probs_vector) {
  return (state_probs_vector[1]) # take only Su - the only up state
}

readiness_over_time_wl <- sapply(0:ITERATIONS_COUNT, function(i)  calculate_readiness_wl(INITIAL_STATE_WL * markov_without_learning ^ i)) 

# plot
#plot(readiness_over_time_wl, ylab="A(t) - BM1WL readiness function", xlab="t", type="l", , col="blue", lwd = 2)
#grid(nx = NULL, ny = NULL,
#     lty = 1,      # Grid line type
#     col = "gray", # Grid line color
#     lwd = 1)      # Grid line width
```

# \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\--

## BM1 with ideal Detection (BM1ID)

```{r}

D_for_ideal_d <- 1
# reuse 1fragment matrix without learnig step + add prob of Sl => Sd to Sd => Su
transElms_ideal_d <- build_next_fragment(transition_matrix_1fragment, D_for_ideal_d)[1:3, 1:3]
transElms_ideal_d[2,1] <- transElms[2,1] + transElms[2, 4]
colnames(transElms_ideal_d) <- all_state_labels[1:3]
rownames(transElms_ideal_d) <- all_state_labels[1:3]


print(transElms_ideal_d)

markov_ideal_d <- new('markovchain',
              transitionMatrix = transElms_ideal_d,
              states = all_state_labels[1:3],
              name = "BM1ID")
```

## Visualize BM1ID

```{r}
plotmat(t(transElms_ideal_d),
        relsize = 1,
        pos = NULL, 
        lwd = 1, # arrow shadow
        box.lwd = 2, shadow.size = 0.003, # shadow
        cex.txt = 0.8, # weight font size
        box.size = 0.03, # state shape size
        box.col = "light blue",
        arr.width = .1, arr.length = .3, arr.pos = 0.4,
        self.cex = .8,
        self.shifty = -.027,
        self.shiftx = -.045,
        main = "Markov Chain - BM1 with ideal Detection")
```

### Readiness calc for BM1ID

```{r}
INITIAL_STATE_ID <- c(1, 0, 0) # Su
calculate_readiness_id <- function(state_probs_vector) {
  return (state_probs_vector[1]) # take only Su - the only up state
}

readiness_over_time_id <- sapply(0:ITERATIONS_COUNT, function(i)  calculate_readiness_id(INITIAL_STATE_ID * markov_ideal_d ^ i)) 

# plot
#plot(readiness_over_time_id, ylab="A(t) - BM1ID readiness function", xlab="t", type="l", col="green", lwd = 2)
#grid(nx = NULL, ny = NULL,
#     lty = 1,      # Grid line type
#     col = "gray", # Grid line color
#     lwd = 1)      # Grid line width
```

# \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\--

## General readiness function

```{r}
# plot
plot(readiness_over_time_wl, ylab="A(t)", xlab="t", type="l",col='blue') 
grid(nx = NULL, ny = NULL, lty = 1, # Grid line type
     col = "gray", # Grid line color 
     lwd = 1) # Grid line width
lines(readiness_over_time, col='red') 
lines(readiness_over_time_id, col='green') 
legend("right", legend=c("With learning", "Without learning", "With ideal fail detection"), col=c("red", "blue", "green"), lty=1:2, cex=0.8, xpd=TRUE, pch = c(10, 15, 1))
```

## Readiness function params calculation

```{r}
print_report_for_rediness_functions(readiness_over_time, readiness_over_time_wl)

stationary_readiness_l <- calculate_readiness(steadyStates(markov))
stationary_readiness_ideal <- calculate_readiness_id(steadyStates(markov_ideal_d))
stationary_readiness_wl <- calculate_readiness_wl(steadyStates(markov_without_learning))
print(paste("steady(A(t)) with learning:   ", stationary_readiness_l))
print(paste("steady(A(t)) without learning:", stationary_readiness_wl))
print(paste("steady(A(t)) with ideal:      ", stationary_readiness_ideal))
```
